//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZongSmsService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="reportRequest", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    public partial class reportRequest : object
    {
        
        private string loginIdField;
        
        private string loginPasswordField;
        
        private string datefromField;
        
        private string datetoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginId
        {
            get
            {
                return this.loginIdField;
            }
            set
            {
                this.loginIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginPassword
        {
            get
            {
                return this.loginPasswordField;
            }
            set
            {
                this.loginPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string datefrom
        {
            get
            {
                return this.datefromField;
            }
            set
            {
                this.datefromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string dateto
        {
            get
            {
                return this.datetoField;
            }
            set
            {
                this.datetoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="reportResponse", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    public partial class reportResponse : object
    {
        
        private string MobileField;
        
        private string MaskingField;
        
        private string MessageField;
        
        private string SentDateField;
        
        private string STATUSField;
        
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile
        {
            get
            {
                return this.MobileField;
            }
            set
            {
                this.MobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Masking
        {
            get
            {
                return this.MaskingField;
            }
            set
            {
                this.MaskingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string SentDate
        {
            get
            {
                return this.SentDateField;
            }
            set
            {
                this.SentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string STATUS
        {
            get
            {
                return this.STATUSField;
            }
            set
            {
                this.STATUSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CampaignsResquest", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    public partial class CampaignsResquest : object
    {
        
        private string loginIdField;
        
        private string loginPasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginId
        {
            get
            {
                return this.loginIdField;
            }
            set
            {
                this.loginIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginPassword
        {
            get
            {
                return this.loginPasswordField;
            }
            set
            {
                this.loginPasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CampaignsResponse", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    public partial class CampaignsResponse : object
    {
        
        private string GroupNameField;
        
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName
        {
            get
            {
                return this.GroupNameField;
            }
            set
            {
                this.GroupNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuickSMSResquest", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    public partial class QuickSMSResquest : object
    {
        
        private string loginIdField;
        
        private string loginPasswordField;
        
        private string DestinationField;
        
        private string MaskField;
        
        private string MessageField;
        
        private string UniCodeField;
        
        private string ShortCodePreferedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginId
        {
            get
            {
                return this.loginIdField;
            }
            set
            {
                this.loginIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginPassword
        {
            get
            {
                return this.loginPasswordField;
            }
            set
            {
                this.loginPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Destination
        {
            get
            {
                return this.DestinationField;
            }
            set
            {
                this.DestinationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Mask
        {
            get
            {
                return this.MaskField;
            }
            set
            {
                this.MaskField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string UniCode
        {
            get
            {
                return this.UniCodeField;
            }
            set
            {
                this.UniCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ShortCodePrefered
        {
            get
            {
                return this.ShortCodePreferedField;
            }
            set
            {
                this.ShortCodePreferedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CounterRequest", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    public partial class CounterRequest : object
    {
        
        private string loginIdField;
        
        private string loginPasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginId
        {
            get
            {
                return this.loginIdField;
            }
            set
            {
                this.loginIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginPassword
        {
            get
            {
                return this.loginPasswordField;
            }
            set
            {
                this.loginPasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CounterResponse", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    public partial class CounterResponse : object
    {
        
        private string Total_BalanceField;
        
        private string Total_BroadcastedField;
        
        private string Total_SuccessfulField;
        
        private string Total_FailedField;
        
        private string User_MasksField;
        
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Total_Balance
        {
            get
            {
                return this.Total_BalanceField;
            }
            set
            {
                this.Total_BalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Total_Broadcasted
        {
            get
            {
                return this.Total_BroadcastedField;
            }
            set
            {
                this.Total_BroadcastedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Total_Successful
        {
            get
            {
                return this.Total_SuccessfulField;
            }
            set
            {
                this.Total_SuccessfulField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Total_Failed
        {
            get
            {
                return this.Total_FailedField;
            }
            set
            {
                this.Total_FailedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string User_Masks
        {
            get
            {
                return this.User_MasksField;
            }
            set
            {
                this.User_MasksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkSMSResquest", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    public partial class BulkSMSResquest : object
    {
        
        private string loginIdField;
        
        private string loginPasswordField;
        
        private string CampaignNameField;
        
        private string MaskField;
        
        private string MessageField;
        
        private string UniCodeField;
        
        private ZongSmsService.numbersList[] lstNLField;
        
        private string CampaignDateField;
        
        private string ShortCodePreferedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginId
        {
            get
            {
                return this.loginIdField;
            }
            set
            {
                this.loginIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginPassword
        {
            get
            {
                return this.loginPasswordField;
            }
            set
            {
                this.loginPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string CampaignName
        {
            get
            {
                return this.CampaignNameField;
            }
            set
            {
                this.CampaignNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Mask
        {
            get
            {
                return this.MaskField;
            }
            set
            {
                this.MaskField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string UniCode
        {
            get
            {
                return this.UniCodeField;
            }
            set
            {
                this.UniCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public ZongSmsService.numbersList[] lstNL
        {
            get
            {
                return this.lstNLField;
            }
            set
            {
                this.lstNLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string CampaignDate
        {
            get
            {
                return this.CampaignDateField;
            }
            set
            {
                this.CampaignDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string ShortCodePrefered
        {
            get
            {
                return this.ShortCodePreferedField;
            }
            set
            {
                this.ShortCodePreferedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="numbersList", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    public partial class numbersList : object
    {
        
        private string NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DynamicSMSRequest", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    public partial class DynamicSMSRequest : object
    {
        
        private string loginIdField;
        
        private string loginPasswordField;
        
        private string MaskField;
        
        private string MessageField;
        
        private ZongSmsService.DynamicList[] lstNLField;
        
        private string CampaignDateField;
        
        private string ShortCodePreferedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginId
        {
            get
            {
                return this.loginIdField;
            }
            set
            {
                this.loginIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginPassword
        {
            get
            {
                return this.loginPasswordField;
            }
            set
            {
                this.loginPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Mask
        {
            get
            {
                return this.MaskField;
            }
            set
            {
                this.MaskField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public ZongSmsService.DynamicList[] lstNL
        {
            get
            {
                return this.lstNLField;
            }
            set
            {
                this.lstNLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string CampaignDate
        {
            get
            {
                return this.CampaignDateField;
            }
            set
            {
                this.CampaignDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ShortCodePrefered
        {
            get
            {
                return this.ShortCodePreferedField;
            }
            set
            {
                this.ShortCodePreferedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DynamicList", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    public partial class DynamicList : object
    {
        
        private string NumberField;
        
        private string Var1Field;
        
        private string Var2Field;
        
        private string Var3Field;
        
        private string Var4Field;
        
        private string Var5Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Var1
        {
            get
            {
                return this.Var1Field;
            }
            set
            {
                this.Var1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Var2
        {
            get
            {
                return this.Var2Field;
            }
            set
            {
                this.Var2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Var3
        {
            get
            {
                return this.Var3Field;
            }
            set
            {
                this.Var3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Var4
        {
            get
            {
                return this.Var4Field;
            }
            set
            {
                this.Var4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Var5
        {
            get
            {
                return this.Var5Field;
            }
            set
            {
                this.Var5Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InboxRequest", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    public partial class InboxRequest : object
    {
        
        private string loginIdField;
        
        private string loginPasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginId
        {
            get
            {
                return this.loginIdField;
            }
            set
            {
                this.loginIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginPassword
        {
            get
            {
                return this.loginPasswordField;
            }
            set
            {
                this.loginPasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InboxResponse", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    public partial class InboxResponse : object
    {
        
        private string MobileField;
        
        private string ReplyField;
        
        private string ReplyDateField;
        
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile
        {
            get
            {
                return this.MobileField;
            }
            set
            {
                this.MobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reply
        {
            get
            {
                return this.ReplyField;
            }
            set
            {
                this.ReplyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReplyDate
        {
            get
            {
                return this.ReplyDateField;
            }
            set
            {
                this.ReplyDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZongSmsService.ICorporateCBS")]
    public interface ICorporateCBS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/GetReports", ReplyAction="http://tempuri.org/ICorporateCBS/GetReportsResponse")]
        System.Threading.Tasks.Task<ZongSmsService.reportResponse[]> GetReportsAsync(ZongSmsService.reportRequest objReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/GetCampaigns", ReplyAction="http://tempuri.org/ICorporateCBS/GetCampaignsResponse")]
        System.Threading.Tasks.Task<ZongSmsService.CampaignsResponse[]> GetCampaignsAsync(ZongSmsService.CampaignsResquest objCampaigns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/QuickSMS", ReplyAction="http://tempuri.org/ICorporateCBS/QuickSMSResponse")]
        System.Threading.Tasks.Task<string> QuickSMSAsync(ZongSmsService.QuickSMSResquest obj_QuickSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/GetAccountSummary", ReplyAction="http://tempuri.org/ICorporateCBS/GetAccountSummaryResponse")]
        System.Threading.Tasks.Task<ZongSmsService.CounterResponse[]> GetAccountSummaryAsync(ZongSmsService.CounterRequest obj_GetAccountSummary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/BulkSMS", ReplyAction="http://tempuri.org/ICorporateCBS/BulkSMSResponse")]
        System.Threading.Tasks.Task<string> BulkSMSAsync(ZongSmsService.BulkSMSResquest obj_BulkSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/DynamicSMS", ReplyAction="http://tempuri.org/ICorporateCBS/DynamicSMSResponse")]
        System.Threading.Tasks.Task<string> DynamicSMSAsync(ZongSmsService.DynamicSMSRequest obj_DynamicSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/GetInbox", ReplyAction="http://tempuri.org/ICorporateCBS/GetInboxResponse")]
        System.Threading.Tasks.Task<ZongSmsService.InboxResponse[]> GetInboxAsync(ZongSmsService.InboxRequest objInbox);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ICorporateCBSChannel : ZongSmsService.ICorporateCBS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class CorporateCBSClient : System.ServiceModel.ClientBase<ZongSmsService.ICorporateCBS>, ZongSmsService.ICorporateCBS
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CorporateCBSClient(EndpointConfiguration endpointConfiguration) : 
                base(CorporateCBSClient.GetBindingForEndpoint(endpointConfiguration), CorporateCBSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CorporateCBSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CorporateCBSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CorporateCBSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CorporateCBSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CorporateCBSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ZongSmsService.reportResponse[]> GetReportsAsync(ZongSmsService.reportRequest objReport)
        {
            return base.Channel.GetReportsAsync(objReport);
        }
        
        public System.Threading.Tasks.Task<ZongSmsService.CampaignsResponse[]> GetCampaignsAsync(ZongSmsService.CampaignsResquest objCampaigns)
        {
            return base.Channel.GetCampaignsAsync(objCampaigns);
        }
        
        public System.Threading.Tasks.Task<string> QuickSMSAsync(ZongSmsService.QuickSMSResquest obj_QuickSMS)
        {
            return base.Channel.QuickSMSAsync(obj_QuickSMS);
        }
        
        public System.Threading.Tasks.Task<ZongSmsService.CounterResponse[]> GetAccountSummaryAsync(ZongSmsService.CounterRequest obj_GetAccountSummary)
        {
            return base.Channel.GetAccountSummaryAsync(obj_GetAccountSummary);
        }
        
        public System.Threading.Tasks.Task<string> BulkSMSAsync(ZongSmsService.BulkSMSResquest obj_BulkSMS)
        {
            return base.Channel.BulkSMSAsync(obj_BulkSMS);
        }
        
        public System.Threading.Tasks.Task<string> DynamicSMSAsync(ZongSmsService.DynamicSMSRequest obj_DynamicSMS)
        {
            return base.Channel.DynamicSMSAsync(obj_DynamicSMS);
        }
        
        public System.Threading.Tasks.Task<ZongSmsService.InboxResponse[]> GetInboxAsync(ZongSmsService.InboxRequest objInbox)
        {
            return base.Channel.GetInboxAsync(objInbox);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICorporateCBS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICorporateCBS1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICorporateCBS))
            {
                return new System.ServiceModel.EndpointAddress("http://cbssvr-01.cmpak.local/ReachCWSv2/CorporateSMS.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICorporateCBS1))
            {
                return new System.ServiceModel.EndpointAddress("https://cbs.zong.com.pk/ReachCWSv2/CorporateSMS.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICorporateCBS,
            
            BasicHttpBinding_ICorporateCBS1,
        }
    }
}
