using System;
using System.Collections.Generic;

namespace PAKDial.Domains.DomainModels
{
    public partial class AutoGeneratedInvoiceNo
    {
        public decimal Id { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public int Increment { get; set; }
    }
}
